version: '3.9'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"  # Accedés en http://localhost:8080
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

networks:
  app-network:
    driver: bridge
